export const VoucherErrorCode = {
  NOT_FOUND: 'VOUCHER_NOT_FOUND',
  NOT_STARTED: 'VOUCHER_NOT_STARTED',
  EXPIRED: 'VOUCHER_EXPIRED',
  DISABLED: 'VOUCHER_DISABLED',
  SHOP_MISMATCH: 'VOUCHER_SHOP_MISMATCH',
  MIN_ORDER_NOT_MET: 'VOUCHER_MIN_ORDER_NOT_MET',
  USAGE_LIMIT_REACHED: 'VOUCHER_USAGE_LIMIT_REACHED',
  USER_LIMIT_REACHED: 'VOUCHER_USER_LIMIT_REACHED',
  SCOPE_CONFLICT: 'VOUCHER_SCOPE_CONFLICT',
} as const;

export type VoucherErrorCode =
  (typeof VoucherErrorCode)[keyof typeof VoucherErrorCode];
